//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleSYSBANK.BankingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfBankingService.DataContract")]
    [System.SerializableAttribute()]
    public partial class AccountDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IBANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UpdateByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> User_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IBAN {
            get {
                return this.IBANField;
            }
            set {
                if ((object.ReferenceEquals(this.IBANField, value) != true)) {
                    this.IBANField = value;
                    this.RaisePropertyChanged("IBAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalBalance {
            get {
                return this.TotalBalanceField;
            }
            set {
                if ((this.TotalBalanceField.Equals(value) != true)) {
                    this.TotalBalanceField = value;
                    this.RaisePropertyChanged("TotalBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UpdateBy {
            get {
                return this.UpdateByField;
            }
            set {
                if ((this.UpdateByField.Equals(value) != true)) {
                    this.UpdateByField = value;
                    this.RaisePropertyChanged("UpdateBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateDate {
            get {
                return this.UpdateDateField;
            }
            set {
                if ((this.UpdateDateField.Equals(value) != true)) {
                    this.UpdateDateField = value;
                    this.RaisePropertyChanged("UpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatementDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfBankingService.DataContract")]
    [System.SerializableAttribute()]
    public partial class StatementDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreateByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FullMoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IBANFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IBANToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrevBalanceFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrevBalanceToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Req_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WithdrawField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel {
            get {
                return this.ChannelField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelField, value) != true)) {
                    this.ChannelField = value;
                    this.RaisePropertyChanged("Channel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreateBy {
            get {
                return this.CreateByField;
            }
            set {
                if ((this.CreateByField.Equals(value) != true)) {
                    this.CreateByField = value;
                    this.RaisePropertyChanged("CreateBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Deposit {
            get {
                return this.DepositField;
            }
            set {
                if ((this.DepositField.Equals(value) != true)) {
                    this.DepositField = value;
                    this.RaisePropertyChanged("Deposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Fee {
            get {
                return this.FeeField;
            }
            set {
                if ((this.FeeField.Equals(value) != true)) {
                    this.FeeField = value;
                    this.RaisePropertyChanged("Fee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FullMoney {
            get {
                return this.FullMoneyField;
            }
            set {
                if ((this.FullMoneyField.Equals(value) != true)) {
                    this.FullMoneyField = value;
                    this.RaisePropertyChanged("FullMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IBANFrom {
            get {
                return this.IBANFromField;
            }
            set {
                if ((object.ReferenceEquals(this.IBANFromField, value) != true)) {
                    this.IBANFromField = value;
                    this.RaisePropertyChanged("IBANFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IBANTo {
            get {
                return this.IBANToField;
            }
            set {
                if ((object.ReferenceEquals(this.IBANToField, value) != true)) {
                    this.IBANToField = value;
                    this.RaisePropertyChanged("IBANTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PrevBalanceFrom {
            get {
                return this.PrevBalanceFromField;
            }
            set {
                if ((this.PrevBalanceFromField.Equals(value) != true)) {
                    this.PrevBalanceFromField = value;
                    this.RaisePropertyChanged("PrevBalanceFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PrevBalanceTo {
            get {
                return this.PrevBalanceToField;
            }
            set {
                if ((this.PrevBalanceToField.Equals(value) != true)) {
                    this.PrevBalanceToField = value;
                    this.RaisePropertyChanged("PrevBalanceTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Req_No {
            get {
                return this.Req_NoField;
            }
            set {
                if ((object.ReferenceEquals(this.Req_NoField, value) != true)) {
                    this.Req_NoField = value;
                    this.RaisePropertyChanged("Req_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Withdraw {
            get {
                return this.WithdrawField;
            }
            set {
                if ((this.WithdrawField.Equals(value) != true)) {
                    this.WithdrawField = value;
                    this.RaisePropertyChanged("Withdraw");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfBankingService.DataContract")]
    [System.SerializableAttribute()]
    public partial class TransactionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreateByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FullMoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IBANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrevBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Req_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WithdrawField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreateBy {
            get {
                return this.CreateByField;
            }
            set {
                if ((this.CreateByField.Equals(value) != true)) {
                    this.CreateByField = value;
                    this.RaisePropertyChanged("CreateBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Deposit {
            get {
                return this.DepositField;
            }
            set {
                if ((this.DepositField.Equals(value) != true)) {
                    this.DepositField = value;
                    this.RaisePropertyChanged("Deposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Fee {
            get {
                return this.FeeField;
            }
            set {
                if ((this.FeeField.Equals(value) != true)) {
                    this.FeeField = value;
                    this.RaisePropertyChanged("Fee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FullMoney {
            get {
                return this.FullMoneyField;
            }
            set {
                if ((this.FullMoneyField.Equals(value) != true)) {
                    this.FullMoneyField = value;
                    this.RaisePropertyChanged("FullMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IBAN {
            get {
                return this.IBANField;
            }
            set {
                if ((object.ReferenceEquals(this.IBANField, value) != true)) {
                    this.IBANField = value;
                    this.RaisePropertyChanged("IBAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PrevBalance {
            get {
                return this.PrevBalanceField;
            }
            set {
                if ((this.PrevBalanceField.Equals(value) != true)) {
                    this.PrevBalanceField = value;
                    this.RaisePropertyChanged("PrevBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Req_No {
            get {
                return this.Req_NoField;
            }
            set {
                if ((object.ReferenceEquals(this.Req_NoField, value) != true)) {
                    this.Req_NoField = value;
                    this.RaisePropertyChanged("Req_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Withdraw {
            get {
                return this.WithdrawField;
            }
            set {
                if ((this.WithdrawField.Equals(value) != true)) {
                    this.WithdrawField = value;
                    this.RaisePropertyChanged("Withdraw");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfBankingService.DataContract")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CitizenIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CitizenID {
            get {
                return this.CitizenIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CitizenIDField, value) != true)) {
                    this.CitizenIDField = value;
                    this.RaisePropertyChanged("CitizenID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportID {
            get {
                return this.PassportIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportIDField, value) != true)) {
                    this.PassportIDField = value;
                    this.RaisePropertyChanged("PassportID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankingService.IWcfBankingService")]
    public interface IWcfBankingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/AddAccount", ReplyAction="http://tempuri.org/IWcfBankingService/AddAccountResponse")]
        int AddAccount(SampleSYSBANK.BankingService.AccountDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/AddAccount", ReplyAction="http://tempuri.org/IWcfBankingService/AddAccountResponse")]
        System.Threading.Tasks.Task<int> AddAccountAsync(SampleSYSBANK.BankingService.AccountDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/UpDateAccount", ReplyAction="http://tempuri.org/IWcfBankingService/UpDateAccountResponse")]
        int UpDateAccount(SampleSYSBANK.BankingService.AccountDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/UpDateAccount", ReplyAction="http://tempuri.org/IWcfBankingService/UpDateAccountResponse")]
        System.Threading.Tasks.Task<int> UpDateAccountAsync(SampleSYSBANK.BankingService.AccountDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/DataAccountBYUser", ReplyAction="http://tempuri.org/IWcfBankingService/DataAccountBYUserResponse")]
        SampleSYSBANK.BankingService.AccountDTO[] DataAccountBYUser(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/DataAccountBYUser", ReplyAction="http://tempuri.org/IWcfBankingService/DataAccountBYUserResponse")]
        System.Threading.Tasks.Task<SampleSYSBANK.BankingService.AccountDTO[]> DataAccountBYUserAsync(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/GetAccountBankRecord", ReplyAction="http://tempuri.org/IWcfBankingService/GetAccountBankRecordResponse")]
        SampleSYSBANK.BankingService.AccountDTO GetAccountBankRecord(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/GetAccountBankRecord", ReplyAction="http://tempuri.org/IWcfBankingService/GetAccountBankRecordResponse")]
        System.Threading.Tasks.Task<SampleSYSBANK.BankingService.AccountDTO> GetAccountBankRecordAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/GetRecordByIBAN", ReplyAction="http://tempuri.org/IWcfBankingService/GetRecordByIBANResponse")]
        SampleSYSBANK.BankingService.AccountDTO GetRecordByIBAN(string iban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/GetRecordByIBAN", ReplyAction="http://tempuri.org/IWcfBankingService/GetRecordByIBANResponse")]
        System.Threading.Tasks.Task<SampleSYSBANK.BankingService.AccountDTO> GetRecordByIBANAsync(string iban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/AddStatement", ReplyAction="http://tempuri.org/IWcfBankingService/AddStatementResponse")]
        int AddStatement(SampleSYSBANK.BankingService.StatementDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/AddStatement", ReplyAction="http://tempuri.org/IWcfBankingService/AddStatementResponse")]
        System.Threading.Tasks.Task<int> AddStatementAsync(SampleSYSBANK.BankingService.StatementDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/UpDateStatement", ReplyAction="http://tempuri.org/IWcfBankingService/UpDateStatementResponse")]
        int UpDateStatement(SampleSYSBANK.BankingService.StatementDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/UpDateStatement", ReplyAction="http://tempuri.org/IWcfBankingService/UpDateStatementResponse")]
        System.Threading.Tasks.Task<int> UpDateStatementAsync(SampleSYSBANK.BankingService.StatementDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/DataStatementByIBAN", ReplyAction="http://tempuri.org/IWcfBankingService/DataStatementByIBANResponse")]
        SampleSYSBANK.BankingService.StatementDTO[] DataStatementByIBAN(string IBAN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/DataStatementByIBAN", ReplyAction="http://tempuri.org/IWcfBankingService/DataStatementByIBANResponse")]
        System.Threading.Tasks.Task<SampleSYSBANK.BankingService.StatementDTO[]> DataStatementByIBANAsync(string IBAN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/GetStatementBankRecord", ReplyAction="http://tempuri.org/IWcfBankingService/GetStatementBankRecordResponse")]
        SampleSYSBANK.BankingService.StatementDTO GetStatementBankRecord(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/GetStatementBankRecord", ReplyAction="http://tempuri.org/IWcfBankingService/GetStatementBankRecordResponse")]
        System.Threading.Tasks.Task<SampleSYSBANK.BankingService.StatementDTO> GetStatementBankRecordAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/GetRecordByReq", ReplyAction="http://tempuri.org/IWcfBankingService/GetRecordByReqResponse")]
        SampleSYSBANK.BankingService.StatementDTO GetRecordByReq(string req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/GetRecordByReq", ReplyAction="http://tempuri.org/IWcfBankingService/GetRecordByReqResponse")]
        System.Threading.Tasks.Task<SampleSYSBANK.BankingService.StatementDTO> GetRecordByReqAsync(string req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/AddTransaction", ReplyAction="http://tempuri.org/IWcfBankingService/AddTransactionResponse")]
        int AddTransaction(SampleSYSBANK.BankingService.TransactionDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/AddTransaction", ReplyAction="http://tempuri.org/IWcfBankingService/AddTransactionResponse")]
        System.Threading.Tasks.Task<int> AddTransactionAsync(SampleSYSBANK.BankingService.TransactionDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/UpDateTransaction", ReplyAction="http://tempuri.org/IWcfBankingService/UpDateTransactionResponse")]
        int UpDateTransaction(SampleSYSBANK.BankingService.TransactionDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/UpDateTransaction", ReplyAction="http://tempuri.org/IWcfBankingService/UpDateTransactionResponse")]
        System.Threading.Tasks.Task<int> UpDateTransactionAsync(SampleSYSBANK.BankingService.TransactionDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/GetAllByIBAN", ReplyAction="http://tempuri.org/IWcfBankingService/GetAllByIBANResponse")]
        SampleSYSBANK.BankingService.TransactionDTO[] GetAllByIBAN(string iban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/GetAllByIBAN", ReplyAction="http://tempuri.org/IWcfBankingService/GetAllByIBANResponse")]
        System.Threading.Tasks.Task<SampleSYSBANK.BankingService.TransactionDTO[]> GetAllByIBANAsync(string iban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/GetTransactionBankRecord", ReplyAction="http://tempuri.org/IWcfBankingService/GetTransactionBankRecordResponse")]
        SampleSYSBANK.BankingService.TransactionDTO GetTransactionBankRecord(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/GetTransactionBankRecord", ReplyAction="http://tempuri.org/IWcfBankingService/GetTransactionBankRecordResponse")]
        System.Threading.Tasks.Task<SampleSYSBANK.BankingService.TransactionDTO> GetTransactionBankRecordAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/AddUser", ReplyAction="http://tempuri.org/IWcfBankingService/AddUserResponse")]
        int AddUser(SampleSYSBANK.BankingService.UserDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/AddUser", ReplyAction="http://tempuri.org/IWcfBankingService/AddUserResponse")]
        System.Threading.Tasks.Task<int> AddUserAsync(SampleSYSBANK.BankingService.UserDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/UpDateUser", ReplyAction="http://tempuri.org/IWcfBankingService/UpDateUserResponse")]
        int UpDateUser(SampleSYSBANK.BankingService.UserDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/UpDateUser", ReplyAction="http://tempuri.org/IWcfBankingService/UpDateUserResponse")]
        System.Threading.Tasks.Task<int> UpDateUserAsync(SampleSYSBANK.BankingService.UserDTO data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/DataUser", ReplyAction="http://tempuri.org/IWcfBankingService/DataUserResponse")]
        SampleSYSBANK.BankingService.UserDTO[] DataUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/DataUser", ReplyAction="http://tempuri.org/IWcfBankingService/DataUserResponse")]
        System.Threading.Tasks.Task<SampleSYSBANK.BankingService.UserDTO[]> DataUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/GetUserBankRecord", ReplyAction="http://tempuri.org/IWcfBankingService/GetUserBankRecordResponse")]
        SampleSYSBANK.BankingService.UserDTO GetUserBankRecord(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfBankingService/GetUserBankRecord", ReplyAction="http://tempuri.org/IWcfBankingService/GetUserBankRecordResponse")]
        System.Threading.Tasks.Task<SampleSYSBANK.BankingService.UserDTO> GetUserBankRecordAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfBankingServiceChannel : SampleSYSBANK.BankingService.IWcfBankingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfBankingServiceClient : System.ServiceModel.ClientBase<SampleSYSBANK.BankingService.IWcfBankingService>, SampleSYSBANK.BankingService.IWcfBankingService {
        
        public WcfBankingServiceClient() {
        }
        
        public WcfBankingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfBankingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfBankingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfBankingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddAccount(SampleSYSBANK.BankingService.AccountDTO data) {
            return base.Channel.AddAccount(data);
        }
        
        public System.Threading.Tasks.Task<int> AddAccountAsync(SampleSYSBANK.BankingService.AccountDTO data) {
            return base.Channel.AddAccountAsync(data);
        }
        
        public int UpDateAccount(SampleSYSBANK.BankingService.AccountDTO data) {
            return base.Channel.UpDateAccount(data);
        }
        
        public System.Threading.Tasks.Task<int> UpDateAccountAsync(SampleSYSBANK.BankingService.AccountDTO data) {
            return base.Channel.UpDateAccountAsync(data);
        }
        
        public SampleSYSBANK.BankingService.AccountDTO[] DataAccountBYUser(int userid) {
            return base.Channel.DataAccountBYUser(userid);
        }
        
        public System.Threading.Tasks.Task<SampleSYSBANK.BankingService.AccountDTO[]> DataAccountBYUserAsync(int userid) {
            return base.Channel.DataAccountBYUserAsync(userid);
        }
        
        public SampleSYSBANK.BankingService.AccountDTO GetAccountBankRecord(int id) {
            return base.Channel.GetAccountBankRecord(id);
        }
        
        public System.Threading.Tasks.Task<SampleSYSBANK.BankingService.AccountDTO> GetAccountBankRecordAsync(int id) {
            return base.Channel.GetAccountBankRecordAsync(id);
        }
        
        public SampleSYSBANK.BankingService.AccountDTO GetRecordByIBAN(string iban) {
            return base.Channel.GetRecordByIBAN(iban);
        }
        
        public System.Threading.Tasks.Task<SampleSYSBANK.BankingService.AccountDTO> GetRecordByIBANAsync(string iban) {
            return base.Channel.GetRecordByIBANAsync(iban);
        }
        
        public int AddStatement(SampleSYSBANK.BankingService.StatementDTO data) {
            return base.Channel.AddStatement(data);
        }
        
        public System.Threading.Tasks.Task<int> AddStatementAsync(SampleSYSBANK.BankingService.StatementDTO data) {
            return base.Channel.AddStatementAsync(data);
        }
        
        public int UpDateStatement(SampleSYSBANK.BankingService.StatementDTO data) {
            return base.Channel.UpDateStatement(data);
        }
        
        public System.Threading.Tasks.Task<int> UpDateStatementAsync(SampleSYSBANK.BankingService.StatementDTO data) {
            return base.Channel.UpDateStatementAsync(data);
        }
        
        public SampleSYSBANK.BankingService.StatementDTO[] DataStatementByIBAN(string IBAN) {
            return base.Channel.DataStatementByIBAN(IBAN);
        }
        
        public System.Threading.Tasks.Task<SampleSYSBANK.BankingService.StatementDTO[]> DataStatementByIBANAsync(string IBAN) {
            return base.Channel.DataStatementByIBANAsync(IBAN);
        }
        
        public SampleSYSBANK.BankingService.StatementDTO GetStatementBankRecord(int id) {
            return base.Channel.GetStatementBankRecord(id);
        }
        
        public System.Threading.Tasks.Task<SampleSYSBANK.BankingService.StatementDTO> GetStatementBankRecordAsync(int id) {
            return base.Channel.GetStatementBankRecordAsync(id);
        }
        
        public SampleSYSBANK.BankingService.StatementDTO GetRecordByReq(string req) {
            return base.Channel.GetRecordByReq(req);
        }
        
        public System.Threading.Tasks.Task<SampleSYSBANK.BankingService.StatementDTO> GetRecordByReqAsync(string req) {
            return base.Channel.GetRecordByReqAsync(req);
        }
        
        public int AddTransaction(SampleSYSBANK.BankingService.TransactionDTO data) {
            return base.Channel.AddTransaction(data);
        }
        
        public System.Threading.Tasks.Task<int> AddTransactionAsync(SampleSYSBANK.BankingService.TransactionDTO data) {
            return base.Channel.AddTransactionAsync(data);
        }
        
        public int UpDateTransaction(SampleSYSBANK.BankingService.TransactionDTO data) {
            return base.Channel.UpDateTransaction(data);
        }
        
        public System.Threading.Tasks.Task<int> UpDateTransactionAsync(SampleSYSBANK.BankingService.TransactionDTO data) {
            return base.Channel.UpDateTransactionAsync(data);
        }
        
        public SampleSYSBANK.BankingService.TransactionDTO[] GetAllByIBAN(string iban) {
            return base.Channel.GetAllByIBAN(iban);
        }
        
        public System.Threading.Tasks.Task<SampleSYSBANK.BankingService.TransactionDTO[]> GetAllByIBANAsync(string iban) {
            return base.Channel.GetAllByIBANAsync(iban);
        }
        
        public SampleSYSBANK.BankingService.TransactionDTO GetTransactionBankRecord(int id) {
            return base.Channel.GetTransactionBankRecord(id);
        }
        
        public System.Threading.Tasks.Task<SampleSYSBANK.BankingService.TransactionDTO> GetTransactionBankRecordAsync(int id) {
            return base.Channel.GetTransactionBankRecordAsync(id);
        }
        
        public int AddUser(SampleSYSBANK.BankingService.UserDTO data) {
            return base.Channel.AddUser(data);
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(SampleSYSBANK.BankingService.UserDTO data) {
            return base.Channel.AddUserAsync(data);
        }
        
        public int UpDateUser(SampleSYSBANK.BankingService.UserDTO data) {
            return base.Channel.UpDateUser(data);
        }
        
        public System.Threading.Tasks.Task<int> UpDateUserAsync(SampleSYSBANK.BankingService.UserDTO data) {
            return base.Channel.UpDateUserAsync(data);
        }
        
        public SampleSYSBANK.BankingService.UserDTO[] DataUser() {
            return base.Channel.DataUser();
        }
        
        public System.Threading.Tasks.Task<SampleSYSBANK.BankingService.UserDTO[]> DataUserAsync() {
            return base.Channel.DataUserAsync();
        }
        
        public SampleSYSBANK.BankingService.UserDTO GetUserBankRecord(int id) {
            return base.Channel.GetUserBankRecord(id);
        }
        
        public System.Threading.Tasks.Task<SampleSYSBANK.BankingService.UserDTO> GetUserBankRecordAsync(int id) {
            return base.Channel.GetUserBankRecordAsync(id);
        }
    }
}
